
# Only one "main" profile is available for now
[profile.main]
# Build command
# example: build_command = "cargo metadata --no-deps --format-version=1 | jq -r '.packages[] | .name as $p | .targets[] | select(.kind[] | index(\"bin\")) | .name as $b | \"\\($p) \\($b)\"' | while read -r p b; do cargo sonic --target-cpus=raptorlake build -p \"$p\" --release --target x86_64-unknown-linux-gnu --bin \"$b\"; done"
build_command = "cargo build --release --target x86_64-unknown-linux-gnu -j 8"

# Which path the binaries are copied from
binary_target = "target/x86_64-unknown-linux-gnu/release"

# Default destination for binaries copied from `binaries` and busybox applets.
# Can be "/bin" or "/usr/bin".
bins_dir = "/usr/bin"

# Binaries to copy
binaries = ["init", "rind", "example-active", "example-inactive", "user_login", "user_shell", "tcp", "ipc_so"]
# Supported forms:
# - "name" -> copied to bins_dir (or /usr/bin by default)
# - "name:/absolute/path"
# - legacy: "bin:name" / "/bin:name" / "usr/bin:name" / "/usr/bin:name"

# Symbolic Links
symlinks = [
  # libs and bins
  "/usr/bin:bin",
  "/usr/lib:/lib",
  "/usr/lib:/lib64",
  "/usr/lib:/usr/lib64"
]

# ldd_bins = ["/usr/bin/init"]

# Files:
# - local copy: "local_path:/dst/path"
# - archive extract: "@alias:member/in/archive:/dst/path"
files = [
  "examples/units:/etc/units",
  "examples/fallback.toml:/etc/fallback.toml",
  "crates/api/examples/api.c:/home/makano/api.c",
  "target/x86_64-unknown-linux-gnu/release/librind_test_plugin.so:/usr/lib/rind/plugins/librind_test_plugin.so",
  "@glibc:usr/bin:/usr/bin",
  "@glibc:var/db:/var/db",
  "@glibc:etc:/etc",
  "@glibc:usr/include:/usr/include",
  "@glibc:usr/lib:/usr/lib",
  "@glibc:usr/share:/usr/share",
  # libs
  "@libasan:usr:/usr",
  "@libatomic:usr:/usr",
  "@libgcc:usr:/usr",
  "@libgfortran:usr:/usr",
  "@libgomp:usr:/usr",
  "@liblsan:usr:/usr",
  "@libobjc:usr:/usr",
  "@libquadmath:usr:/usr",
  "@libstdcpp:usr:/usr",
  "@libtsan:usr:/usr",
  "@libubsan:usr:/usr",

  # libs extra
  "@libidn2:usr:/usr",
  "@libnghttp2:usr:/usr",
  "@libnghttp3:usr:/usr",
  "@libngtcp2:usr:/usr",
  "@libssh2:usr:/usr",
  "@libpsl:usr:/usr",
  "@libunistring:usr:/usr",

  # gcc
  "@gcc:usr:/usr",
  "@libmpc:usr:/usr",
  "@libisl:usr:/usr",
  "@gmp:usr:/usr",
  "@mpfr:usr:/usr",

  # deps
  "@binutils:usr:/usr",
  "@jansson:usr:/usr",
  "@libelf:usr:/usr",
  "@bzip2:usr:/usr",
  "@json-c:usr:/usr",
  "@xz:usr:/usr",
  "@openssl:usr:/usr",
  "@brotli:usr:/usr",
  "@zlib:usr:/usr",
  "@zstd:usr:/usr",
  "@openssl:usr:/usr",
  "@krb5:usr:/usr",
  "@ca-certificates:usr:/usr",
  "@e2fsprogs:usr:/usr",
  "@keyutils:usr:/usr",
  "@linux-headers:usr/lib/modules/6.19.11-arch1-1/build/include/uapi:/usr/include",
  "@linux-headers:usr/lib/modules/6.19.11-arch1-1/build/arch/x86/include/uapi:/usr/include",
  "@linux-headers:usr/lib/modules/6.19.11-arch1-1/build/arch/x86/include/generated/uapi:/usr/include",

  # utils
  "@socat:usr:/usr",
  "@readline:usr:/usr",
  "@ncurses:usr:/usr",
  "@curl:usr:/usr",
]

# Installer cache sources:
# - "https://..."
# - "alias:https://..."
install = [
  "glibc:https://mirror.moson.org/arch/core/os/x86_64/glibc-2.43+r5+g856c426a7534-1-x86_64.pkg.tar.zst",

  # libs
  "libasan:https://archlinux.org/packages/core/x86_64/libasan/download",
  "libatomic:https://archlinux.org/packages/core/x86_64/libatomic/download",
  "libgcc:https://archlinux.org/packages/core/x86_64/libgcc/download",
  "libgfortran:https://archlinux.org/packages/core/x86_64/libgfortran/download",
  "libgomp:https://archlinux.org/packages/core/x86_64/libgomp/download",
  "liblsan:https://archlinux.org/packages/core/x86_64/liblsan/download",
  "libobjc:https://archlinux.org/packages/core/x86_64/libobjc/download",
  "libquadmath:https://archlinux.org/packages/core/x86_64/libquadmath/download",
  "libstdcpp:https://archlinux.org/packages/core/x86_64/libstdc++/download",
  "libtsan:https://archlinux.org/packages/core/x86_64/libtsan/download",
  "libubsan:https://archlinux.org/packages/core/x86_64/libubsan/download",
  "libubsan:https://archlinux.org/packages/core/x86_64/libubsan/download",

  # libs extra
  "libidn2:https://archlinux.org/packages/core/x86_64/libidn2/download",
  "libnghttp2:https://archlinux.org/packages/core/x86_64/libnghttp2/download",
  "libnghttp3:https://archlinux.org/packages/core/x86_64/libnghttp3/download",
  "libngtcp2:https://archlinux.org/packages/core/x86_64/libngtcp2/download",
  "libssh2:https://archlinux.org/packages/core/x86_64/libssh2/download",
  "libpsl:https://archlinux.org/packages/core/x86_64/libpsl/download",
  "libunistring:https://archlinux.org/packages/core/x86_64/libunistring/download",

  # gcc
  "gcc:https://archlinux.org/packages/core/x86_64/gcc/download",
  "libmpc:https://archlinux.org/packages/core/x86_64/libmpc/download",
  "libisl:https://archlinux.org/packages/core/x86_64/libisl/download",
  "gmp:https://archlinux.org/packages/core/x86_64/gmp/download",
  "mpfr:https://archlinux.org/packages/core/x86_64/mpfr/download",

  # deps
  "binutils:https://archlinux.org/packages/core/x86_64/binutils/download",
  "jansson:https://archlinux.org/packages/core/x86_64/jansson/download",
  "libelf:https://archlinux.org/packages/core/x86_64/libelf/download",
  "bzip2:https://archlinux.org/packages/core/x86_64/bzip2/download",
  "json-c:https://archlinux.org/packages/core/x86_64/json-c/download",
  "xz:https://archlinux.org/packages/core/x86_64/xz/download",
  "openssl:https://archlinux.org/packages/core/x86_64/openssl/download",
  "brotli:https://archlinux.org/packages/core/x86_64/brotli/download",
  "zlib:https://archlinux.org/packages/core/x86_64/zlib/download",
  "zstd:https://archlinux.org/packages/core/x86_64/zstd/download",
  "openssl:https://archlinux.org/packages/core/x86_64/openssl/download",
  "krb5:https://archlinux.org/packages/core/x86_64/krb5/download",
  "ca-certificates:https://archlinux.org/packages/core/any/ca-certificates/download",
  "e2fsprogs:https://archlinux.org/packages/core/x86_64/e2fsprogs/download",
  "keyutils:https://archlinux.org/packages/core/x86_64/keyutils/download",
  "linux-headers:https://archlinux.org/packages/core/x86_64/linux-headers/download",

  # utils
  "socat:https://archlinux.org/packages/extra/x86_64/socat/download",
  "readline:https://archlinux.org/packages/core/x86_64/readline/download",
  "ncurses:https://archlinux.org/packages/core/x86_64/ncurses/download",
  "curl:https://archlinux.org/packages/core/x86_64/curl/download",
]

# C header files and static libs
libs = [
  "Crind-api:rind:crates/api"
]

# Busybox Setup
busybox_url = "https://busybox.net/downloads/binaries/1.19.0/busybox-x86_64"

# Use images for now, cpio is depricated
disk_mode = "image"

# Linux Image: for now we can use bzImage
linux_image = "bzImage:https://l4re.org/download/Linux-kernel/x86-64/bzImage-6.6.8"

# root= is needed for image disks
run_options = ["console=ttyS0/ root=/dev/vda rw"]
#qemu_options = { arch = "x86_64", args = [...] }

# Depricated
nodes = [
  # { path = "/dev/null", node_type = "c", major = 1, minor = 3, mode = 0o666 },
  # { path = "/dev/console", node_type = "c", major = 5, minor = 1, mode = 0o666 }
]

# format: /file:uid:gid:mode
disk_permissions = [
  "/usr/bin/rind:0:0:4755"
]

# Supported root env forms (written to /etc/rind/root.env):
# root_env = { RIND = "v0" }
# root_env = ["RIND", "v0"]
# root_envs = ["RIND", "v0"] # legacy alias
root_envs = [
  "RIND", "v0",
  "CPATH", "/usr/include",
  "TEST", "some-test"
]

[[profile.main.user]]
username = "makano"
password = "a"
uid = 1000
gid = 1000
home = "/home/makano"
shell = "/usr/bin/sh"
groups = ["wheel", { name = "network", gid = 1003 }]
# Supported env forms:
# env = { PATH = "/usr/bin:/bin", TERM = "linux" }
# env = ["PATH", "/usr/bin:/bin", "TERM", "linux"]
env = [
  "PATH", "/usr/bin"
]

[[profile.main.user]]
username = "root"
uid = 0
gid = 0
home = "/root"
shell = "/bin/sh"
env = [
  "TEST", "1"
]
