[[service]]
name = "test"
run.exec = "/bin/tcp"
run.args = ["makano-test"]
space = "user"
start-on = [{ state = "rind@user_session" }]

[[service]]
name = "something"
run.exec = "/bin/tcp"
run.args = ["makano-test"]
run.env = { PORT = "4433" }
space = "user"

[[service]]
name = "many"
run.variable = "someservice"
space = "user"
start-on = [{ state = "rind@user_session" }, { state = "rind@net-configured" }]

[[variable]]
name = "someservice"
default = { exec = "/bin/tcp", args = ["makano-test"], env = { PORT = "4533" } }
